### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by basraayman** [yanbxr/d2hosting#2]
This is code that was created initially by other people. Credits have been removed/altered to show this as the persons own code, but it is a 1:1 copy of older sources that have the original credits still intact. An example can be seen in this commit which predates with the exact same code except for the credits:  https://github.com/opwer159/Destiny/commit/8909b5940be2b8ddb7db2d2f3df32a4bb1e84ba7

Please fix the credits to the original code authors and add yourself for any modifications to fix the license issues, otherwise a DMCA takedown request will need to be submitted.

**Comment by yanbxr** [comment]
Credits added
